apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ upper .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ upper .Release.Name }}
  type: ClusterIP  
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}